name: HelpingHand
packages:
  OpenAI:
    url: https://github.com/MacPaw/OpenAI.git
    version: 0.2.4
options:
  bundleIdPrefix: com.example
  deploymentTarget: 
    iOS: 15.0
  xcodeFlags:
    ENABLE_HARDENED_RUNTIME: YES
targets:
  HelpingHand:
    type: application
    platform: iOS
    sources: 
      - App
    settings:
      base:
        INFOPLIST_FILE: App/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.example.helpinghand
      configs:
        debug:
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
        release:
          SWIFT_COMPILATION_MODE: wholemodule
    dependencies:
      - package: OpenAI
